# Generated by Django 4.2.3 on 2023-07-11 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("messagebox", "0002_message_create_time_message_last_update_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="create_time",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="message",
            name="last_update_time",
        ),
        migrations.AddField(
            model_name="message",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
