# Generated by Django 4.2.3 on 2023-07-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0003_alter_message_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
