# Generated by Django 4.2.3 on 2023-07-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0005_alter_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, unique_for_date='date'),
        ),
    ]
