# Generated by Django 4.2.3 on 2023-08-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0008_alter_message_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(default='default title', max_length=40),
        ),
    ]
