# Generated by Django 4.2.3 on 2023-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagebox', '0009_alter_message_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
